### ISSUE TITLE
error 035: argument type mismatch (argument 4)

### ISSUE THREAD

**Issue by ajam123** [Nickk888SAMP/Dialog-Pages#4]
error 035: argument type mismatch (argument 4)

line:  return ShowPlayerDialog(playerid, dialogid, style, caption, info, button1, button2);

tested on new version.

**Comment by Nickk888SAMP** [comment]
Can you send me some more code? Because i can't reproduce this error.

Doing
```pawn
CMD:test(playerid, params[])
{
	ShowPlayerDialog(playerid, 243, DIALOG_STYLE_LIST, "Test1", "info", "test3", "test4", 10);
	return 1;
}
```
Shows me 0 errors.
