### ISSUE TITLE
Argument type mistmatch (argument 4)

### ISSUE THREAD

**Issue by Matei02Mihai** [Nickk888SAMP/Dialog-Pages#5]
Why?????

![Captură](https://user-images.githubusercontent.com/52253354/185740337-413e4fc3-e396-4898-bcd2-a97cfc3736d6.PNG)

**Comment by Nickk888SAMP** [comment]
What Code are you using in your Gamemode or Filterscript? I need more Information.

**Comment by Matei02Mihai** [comment]
https://pastebin.com/sRKLyBG4

**Comment by Nickk888SAMP** [comment]
Ok, could you try downloading the YSI package so the library can use the y_hooks and y_va libraries? It might be a problem with the _ALS_ hooking method but I need to test it further.

**Comment by Nickk888SAMP** [comment]
But it could also be because of the pragma in line 234... Try deleting this line and test it again. I think the compilator can't find the "info" parameter because of the "unused" pragma. Just a theory, I need to test it.

**Comment by Matei02Mihai** [comment]
I tried both solutions, but no result.

**Comment by Nickk888SAMP** [comment]
Alright, I'll look into this today and will put an update. I'll let you know.

**Comment by Nickk888SAMP** [comment]
So, i have probably fixed it in version 3.1.0, download the latest content from the Release tab.
If some problems still occur, please open a new issue.

**Comment by Matei02Mihai** [comment]
That version works. Thank you for helping me!
