### ISSUE TITLE
Version 3.0.0 inputtext limitation

### ISSUE THREAD

**Issue by ZantetsukenGT** [Nickk888SAMP/Dialog-Pages#7]
I'm currently having an issue when I updated to the latest version, in which I need the inputtext string in the response function but I'm unable to obtain it, this is probably a limitation due to how callbacks work.

You're already storing all the info in arrays, so I suggest adding an API to pass in a buffer and get the text from the selected listitem, i cannot think however of an easy way of limiting its usage only within a positive response:

```pawn
stock GetDialogInputText(playerid, listitem, inputtext[])
//or
stock DP_GetInputText(playerid, listitem, inputtext[])
//or
stock PagesGetInputText(playerid, listitem, inputtext[])
//or
stock DialogPagesGetInputText(playerid, listitem, inputtext[])
//or any really
stock GetInputTextDialogPages(playerid, listitem, inputtext[])
```

It is your call, but if there's actually a way to get the text, please let me know

**Comment by Nickk888SAMP** [comment]
You want to obtain the "inputtext" from the dialog right? The text from DIALOG_STYLE_INPUT? If so, the library isn't designed for that, only lists.

Or do you mean getting the list items string? In that case it isn't that difficult as you mentioned it's already saved in the array.

**Comment by ZantetsukenGT** [comment]
Only the selected item's text.
From the samp [docs](https://open.mp/docs/scripting/callbacks/OnDialogResponse):
```
inputtext[] - The text entered into the input box by the player or the selected list item text.
```

**Comment by Nickk888SAMP** [comment]
Oh well, it also returns the selected item inside inputtext? The more you know! Didn't know that! I'll look into this and will push an update soon :)

**Comment by ZantetsukenGT** [comment]
I think it may be easier than I thought, for some reason I thought CallLocalFunction didn't support passing in strings.

From the samp [docs](https://open.mp/docs/scripting/functions/CallLocalFunction):

```pawn
forward publicFunc(number, Float:flt, const string[]);
public publicFunc(number, Float:flt, const string[])
{
    printf("Received integer %i, float %f, string %s", number, flt, string);
    return 1;
}

CallLocalFunction("publicFunc", "ifs", 420, 68.999999999, "Hello world");
```
Just pass in the inputtext variable with an `s` specifier [here](https://github.com/Nickk888SAMP/Dialog-Pages/blob/9dd05d084004584606a67ed29a8842bdbe8695b7/ndialog-pages.inc#L415), that's the exact feature I'm looking for, and no need for extra API's.

I'll do that myself in a new PR to save you some time.
